### PR TITLE
Add option to turn off DNSCrypt and use regular DNS

### LINKED ISSUE #35: Requests
Hi guys,

Thanks for the great script! Ii have 2 requests:

1. Would it be possible to add an option/entry in the menu to switch to non-encrypted dns without having to uninstall? And back again? Like some sort of pause/resume option.
I sometimes cannot use encrypted dns when I need to connect to a company vpn. I can connect to the vpn server but this does not understand the encrypted dns requests...
2. Is a ppa an idea?

Bye
Hans

### PR DESCRIPTION
**Pull request by lucaspetter**
Summary of changes:
- **Feature to turn off DNSCrypt and use regular, unencrypted DNS.** You no longer need to completely uninstall/reinstall to switch back and forth between DNSCrypt and regular DNS, you can now just turn it off/on quickly. This fixes #35 (except for the part about making a PPA).
- **Updated management of resolv.conf and resolv.conf-dnscryptbak.** This is to facilitate the new *off* feature so the backup doesn't get lost when the user re-enables DNSCrypt after turning it off.
- **Changes to the text user interface.** Mainly for using the *off* feature, but also for clarity.

Tested with `dnscrypt-autoinstall.sh` and I can confirm everything works. I haven't tested `dnscrypt-autoinstall-redhat.sh`, but don't foresee any issues.

### CODE REVIEW

**Comment by simonclausen** [comment]
I'll have to come to back to this one later

**Comment by lucaspetter** [comment]
So I thought I could resolve a merge conflict in README.md myself by updating it to the latest code from `simonclausen/dnscrypt-autoinstall/master`. But now the diff view for this PR shows tons of changes for README.md, even tough it's the same as in master.

Should I leave the merge conflicts for you to resolve? I want to help, but don't want to make anything more confusing/complicated. :cold_sweat:

**Comment by simonclausen** [comment]
I really appreciate your help - it is great to see contributions going far beyond what I originally imagines with this little project. So no worries about that :)

That said, I probably won't find peace of mind to sit down and do any actual work on this in the near future, so if you would like to go ahead with fixing it, you are very welcome.

**Comment by lucaspetter** [comment]
Okay, I'll try fixing the merge conflicts soon. I'm only using the web version of GitHub, which doesn't actually highlight conflicts, and the diff view for this pull request may get pretty big/complex as I commit all the latest updates from master. I haven't really dealt with fixing conflicts before, so am hoping I don't mess up and have to start fresh with a new pull request!

**Comment by lucaspetter** [comment]
I've fixed the merge conflicts in #65.

**Pull request closed without merging**
