### PR TITLE
Fakeroot

### PR DESCRIPTION
**Pull request by AladW**
See #64. Not everything is done, but it solves most of the reported issues with the old scripts. Note that latter are left in the legacy branch, as sysvinit support is not implemented yet.

### CODE REVIEW

**Comment by AladW** [comment]
@simonclausen

**Comment by simonclausen** [comment]
@AladW - nice job. I will find time to go through it this weekend.

**Comment by simonclausen** [comment]
Alright, had a chance to look at it. Again, great work, thanks for taking the time!

First of all, I've gone though everything to get an overview of what you've done. I have to say I'm really pleased with the direction you've taken with this re-write: building modularity, "single-script-to-support-all", using dnscrypt-resolvers.csv, explicit "autoinstall" service, and all the other improvements and solved issues.

I have come across the following details in the code, that I've changed:
- Variables for the -backup.service file were missing
- Hardcoded url in sd_url variable pointing to fakeroot branch

Apart from this, I've done a couple of quick install tests on Ubuntu 14.04, Ubuntu 16.04, RedHat 7.2, CentOS 7.2 (minimal), Debian 8 and OpenSUSE 13.2.
- Ubuntu 14.04 failed (of course - no systemd)
- Ubunto 16.04 I get an error on what looks to be the second http call made (https://github.com/simonclausen/dnscrypt-autoinstall/blob/fakeroot/dnscrypt-autoinstall#L42): `curl: (22) The requested URL returned error: 404 Not Found`. This happens right after awk (https://github.com/simonclausen/dnscrypt-autoinstall/blob/fakeroot/dnscrypt-autoinstall#L25) throws a warning: `awk: warning: escape sequence `\.' treated as plain `.'`
- Debian 8 worked without error
- RedHat/CentOS: it seems the "fakeroot" package is not available out of the box, thus failing the install.
- OpenSUSE failed with an error on the first usage of "install" (https://github.com/simonclausen/dnscrypt-autoinstall/blob/fakeroot/dnscrypt-autoinstall#L399): `install: invalid group 'dnscrypt-build'`

How would you like to go about this?

I'm fine with replacing the old stuff now and just being specific in the README about limitations and/or manual steps needed (i.e. EPEL) to start off with. But the thing happening with Ubuntu 16.04 probably needs to be looked at. Sorry I have not been able to find time to dive deeper into this.

**Comment by AladW** [comment]
Thanks for the detailed report; I'll look over these issues when I get the chance.

**Comment by AladW** [comment]
+ Ubuntu 16.04: I can't reproduce this as of writing, but the dnscrypt.org links are shakey and fail from time to time. Needs further investigation.
+ OpenSUSE: It seems useradd doesn't automatically create a matching group for the created user. Changing the install command to e.g `install -o dnscrypt-build -g root -m 750` does the trick.
A more difficult issue is that fakeroot is not available in any official repository.
+ RHEL: fakeroot can be retrieved directly from EPEL, first by importing the EPEL gpg key, and then installing the packages with RPM.
https://getfedora.org/static/352C64E5.txt
https://dl.fedoraproject.org/pub/epel/7/x86_64/f/

**Comment by AladW** [comment]
The commits above should improve the situation (sorry, forgot to set up my git identity). There's still an error on CentOS 7 on tarring dnscrypt-proxy.

**Comment by AladW** [comment]
@simonclausen it now works for me on Ubuntu 16.04, CentOS 7 and openSUSE Leap.

**Comment by simonclausen** [comment]
@AladW, I can validate that Ubuntu 16.04, CentOS 7.2, Debian 8 and OpenSUSE 42.1 works.

But RedHat 7.2 fails: apparently redhat_epel_fakeroot function is failing because RedHat sets the VERSION_ID var to "7.2" and not "7", breaking the case, thus not installing fakeroot.

**Comment by simonclausen** [comment]
Alright, that should cover it for now.

I'm good with merging to master, if you are.

**Comment by AladW** [comment]
Good catch, I've also expanded the check for an eventual minor version in RHEL 6.x. Thanks!

**Pull request merged**
